[package]
name = "ec"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Elliptic Curve Cryptography in Pure Rust"
repository = "https://github.com/sorpaas/ec-rs"

[dependencies]
